// Generated by scripts/gen-db-types.ts from supabase/migrations. Do not edit by hand.
// Regenerate: npm run db:types:local  (or, once linked: npm run db:types)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      bookings: {
        Row: {
          id: string;
          user_id: string;
          mentor_id: string;
          slot_id: string;
          status: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          mentor_id: string;
          slot_id: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          mentor_id?: string;
          slot_id?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'bookings_mentor_id_fkey';
            columns: ['mentor_id'];
            isOneToOne: false;
            referencedRelation: 'mentors';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'bookings_slot_id_fkey';
            columns: ['slot_id'];
            isOneToOne: true;
            referencedRelation: 'mentor_slots';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'bookings_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      calendar_events: {
        Row: {
          id: string;
          kind: string;
          title_en: string;
          title_bn: string;
          starts_on: string;
          ends_on: string | null;
          is_approximate: boolean;
          source_url: string | null;
        };
        Insert: {
          id?: string;
          kind: string;
          title_en: string;
          title_bn: string;
          starts_on: string;
          ends_on?: string | null;
          is_approximate?: boolean;
          source_url?: string | null;
        };
        Update: {
          id?: string;
          kind?: string;
          title_en?: string;
          title_bn?: string;
          starts_on?: string;
          ends_on?: string | null;
          is_approximate?: boolean;
          source_url?: string | null;
        };
        Relationships: [];
      };
      career_paths: {
        Row: {
          id: string;
          title_en: string;
          title_bn: string;
          sector: string;
          description_en: string;
          description_bn: string;
          skills: string[];
          typical_entry_route_en: string;
          typical_entry_route_bn: string;
        };
        Insert: {
          id?: string;
          title_en: string;
          title_bn: string;
          sector: string;
          description_en: string;
          description_bn: string;
          skills?: string[];
          typical_entry_route_en: string;
          typical_entry_route_bn: string;
        };
        Update: {
          id?: string;
          title_en?: string;
          title_bn?: string;
          sector?: string;
          description_en?: string;
          description_bn?: string;
          skills?: string[];
          typical_entry_route_en?: string;
          typical_entry_route_bn?: string;
        };
        Relationships: [];
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          user_id: string | null;
          alias_display: string;
          body: string;
          is_anonymous: boolean;
          report_count: number;
          is_hidden: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id?: string | null;
          alias_display?: string;
          body: string;
          is_anonymous?: boolean;
          report_count?: number;
          is_hidden?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          user_id?: string | null;
          alias_display?: string;
          body?: string;
          is_anonymous?: boolean;
          report_count?: number;
          is_hidden?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'comments_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'comments_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      districts: {
        Row: {
          slug: string;
          division_slug: string;
          name_en: string;
          name_bn: string;
        };
        Insert: {
          slug: string;
          division_slug: string;
          name_en: string;
          name_bn: string;
        };
        Update: {
          slug?: string;
          division_slug?: string;
          name_en?: string;
          name_bn?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'districts_division_slug_fkey';
            columns: ['division_slug'];
            isOneToOne: false;
            referencedRelation: 'divisions';
            referencedColumns: ['slug'];
          },
        ];
      };
      divisions: {
        Row: {
          slug: string;
          name_en: string;
          name_bn: string;
          sort_order: number;
        };
        Insert: {
          slug: string;
          name_en: string;
          name_bn: string;
          sort_order?: number;
        };
        Update: {
          slug?: string;
          name_en?: string;
          name_bn?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      game_scores: {
        Row: {
          id: string;
          user_id: string;
          game_code: string;
          score: number;
          duration_seconds: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          game_code: string;
          score: number;
          duration_seconds: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          game_code?: string;
          score?: number;
          duration_seconds?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'game_scores_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      helplines: {
        Row: {
          id: string;
          name: string;
          number: string;
          description_en: string;
          description_bn: string;
          hours: string;
          category: string;
          is_toll_free: boolean | null;
          source_url: string;
          verified_at: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          name: string;
          number: string;
          description_en: string;
          description_bn: string;
          hours: string;
          category: string;
          is_toll_free?: boolean | null;
          source_url: string;
          verified_at: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          name?: string;
          number?: string;
          description_en?: string;
          description_bn?: string;
          hours?: string;
          category?: string;
          is_toll_free?: boolean | null;
          source_url?: string;
          verified_at?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      journal_entries: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          body: string;
          prompt_id: string | null;
          mood_score: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          title?: string | null;
          body: string;
          prompt_id?: string | null;
          mood_score?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string | null;
          body?: string;
          prompt_id?: string | null;
          mood_score?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'journal_entries_prompt_id_fkey';
            columns: ['prompt_id'];
            isOneToOne: false;
            referencedRelation: 'journal_prompts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'journal_entries_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      journal_prompts: {
        Row: {
          id: string;
          text_en: string;
          text_bn: string;
          category: string;
        };
        Insert: {
          id?: string;
          text_en: string;
          text_bn: string;
          category: string;
        };
        Update: {
          id?: string;
          text_en?: string;
          text_bn?: string;
          category?: string;
        };
        Relationships: [];
      };
      mentor_slots: {
        Row: {
          id: string;
          mentor_id: string;
          starts_at: string;
          ends_at: string;
          is_booked: boolean;
        };
        Insert: {
          id?: string;
          mentor_id: string;
          starts_at: string;
          ends_at: string;
          is_booked?: boolean;
        };
        Update: {
          id?: string;
          mentor_id?: string;
          starts_at?: string;
          ends_at?: string;
          is_booked?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'mentor_slots_mentor_id_fkey';
            columns: ['mentor_id'];
            isOneToOne: false;
            referencedRelation: 'mentors';
            referencedColumns: ['id'];
          },
        ];
      };
      mentors: {
        Row: {
          id: string;
          name: string;
          avatar_seed: string;
          expertise: string[];
          languages: string[];
          bio_en: string;
          bio_bn: string;
          division: string | null;
          rating: number;
          is_active: boolean;
          is_fictional: boolean;
        };
        Insert: {
          id?: string;
          name: string;
          avatar_seed: string;
          expertise?: string[];
          languages?: string[];
          bio_en: string;
          bio_bn: string;
          division?: string | null;
          rating?: number;
          is_active?: boolean;
          is_fictional?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          avatar_seed?: string;
          expertise?: string[];
          languages?: string[];
          bio_en?: string;
          bio_bn?: string;
          division?: string | null;
          rating?: number;
          is_active?: boolean;
          is_fictional?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'mentors_division_fkey';
            columns: ['division'];
            isOneToOne: false;
            referencedRelation: 'divisions';
            referencedColumns: ['slug'];
          },
        ];
      };
      mood_entries: {
        Row: {
          id: string;
          user_id: string;
          score: number;
          emotion_tags: string[];
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          score: number;
          emotion_tags?: string[];
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          score?: number;
          emotion_tags?: string[];
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'mood_entries_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      post_likes: {
        Row: {
          post_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          post_id: string;
          user_id?: string;
          created_at?: string;
        };
        Update: {
          post_id?: string;
          user_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'post_likes_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'post_likes_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      posts: {
        Row: {
          id: string;
          user_id: string | null;
          alias_display: string;
          body: string;
          tags: string[];
          is_anonymous: boolean;
          like_count: number;
          comment_count: number;
          report_count: number;
          is_hidden: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          alias_display?: string;
          body: string;
          tags?: string[];
          is_anonymous?: boolean;
          like_count?: number;
          comment_count?: number;
          report_count?: number;
          is_hidden?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          alias_display?: string;
          body?: string;
          tags?: string[];
          is_anonymous?: boolean;
          like_count?: number;
          comment_count?: number;
          report_count?: number;
          is_hidden?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'posts_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      practitioners: {
        Row: {
          id: string;
          full_name: string;
          title: string;
          profession: string;
          credentials: string | null;
          organization: string;
          specialties: string[];
          languages: string[];
          division_slug: string | null;
          city: string | null;
          modes: string[];
          booking_url: string;
          profile_url: string | null;
          source_url: string;
          verified_at: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          full_name: string;
          title: string;
          profession: string;
          credentials?: string | null;
          organization: string;
          specialties?: string[];
          languages?: string[];
          division_slug?: string | null;
          city?: string | null;
          modes?: string[];
          booking_url: string;
          profile_url?: string | null;
          source_url: string;
          verified_at: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          full_name?: string;
          title?: string;
          profession?: string;
          credentials?: string | null;
          organization?: string;
          specialties?: string[];
          languages?: string[];
          division_slug?: string | null;
          city?: string | null;
          modes?: string[];
          booking_url?: string;
          profile_url?: string | null;
          source_url?: string;
          verified_at?: string;
          is_active?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'practitioners_division_slug_fkey';
            columns: ['division_slug'];
            isOneToOne: false;
            referencedRelation: 'divisions';
            referencedColumns: ['slug'];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string;
          anonymous_alias: string;
          avatar_seed: string;
          division: string | null;
          university_id: string | null;
          locale: string;
          goals: string[];
          xp: number;
          level: number;
          current_streak: number;
          longest_streak: number;
          last_active_date: string | null;
          onboarding_done: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          anonymous_alias: string;
          avatar_seed: string;
          division?: string | null;
          university_id?: string | null;
          locale?: string;
          goals?: string[];
          xp?: number;
          level?: number;
          current_streak?: number;
          longest_streak?: number;
          last_active_date?: string | null;
          onboarding_done?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string;
          anonymous_alias?: string;
          avatar_seed?: string;
          division?: string | null;
          university_id?: string | null;
          locale?: string;
          goals?: string[];
          xp?: number;
          level?: number;
          current_streak?: number;
          longest_streak?: number;
          last_active_date?: string | null;
          onboarding_done?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_division_fkey';
            columns: ['division'];
            isOneToOne: false;
            referencedRelation: 'divisions';
            referencedColumns: ['slug'];
          },
          {
            foreignKeyName: 'profiles_university_id_fkey';
            columns: ['university_id'];
            isOneToOne: false;
            referencedRelation: 'universities';
            referencedColumns: ['id'];
          },
        ];
      };
      quests: {
        Row: {
          id: string;
          code: string;
          title_en: string;
          title_bn: string;
          xp_reward: number;
          type: string;
          completion: string;
          is_active: boolean;
          sort_order: number;
        };
        Insert: {
          id?: string;
          code: string;
          title_en: string;
          title_bn: string;
          xp_reward: number;
          type: string;
          completion?: string;
          is_active?: boolean;
          sort_order?: number;
        };
        Update: {
          id?: string;
          code?: string;
          title_en?: string;
          title_bn?: string;
          xp_reward?: number;
          type?: string;
          completion?: string;
          is_active?: boolean;
          sort_order?: number;
        };
        Relationships: [];
      };
      quiz_results: {
        Row: {
          id: string;
          user_id: string;
          result_career_ids: string[];
          answers: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          result_career_ids?: string[];
          answers: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          result_career_ids?: string[];
          answers?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'quiz_results_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      reports: {
        Row: {
          id: string;
          reporter_id: string;
          post_id: string | null;
          comment_id: string | null;
          reason: string;
          details: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reporter_id?: string;
          post_id?: string | null;
          comment_id?: string | null;
          reason: string;
          details?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          reporter_id?: string;
          post_id?: string | null;
          comment_id?: string | null;
          reason?: string;
          details?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'reports_comment_id_fkey';
            columns: ['comment_id'];
            isOneToOne: false;
            referencedRelation: 'comments';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'reports_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'reports_reporter_id_fkey';
            columns: ['reporter_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      resources: {
        Row: {
          id: string;
          title_en: string;
          title_bn: string | null;
          category: string;
          url: string;
          source_org: string;
          language: string;
          is_verified: boolean;
          verified_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title_en: string;
          title_bn?: string | null;
          category: string;
          url: string;
          source_org: string;
          language: string;
          is_verified?: boolean;
          verified_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          title_en?: string;
          title_bn?: string | null;
          category?: string;
          url?: string;
          source_org?: string;
          language?: string;
          is_verified?: boolean;
          verified_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      resumes: {
        Row: {
          id: string;
          user_id: string;
          data: Json;
          template: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          data?: Json;
          template?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          data?: Json;
          template?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'resumes_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      support_organizations: {
        Row: {
          id: string;
          name_en: string;
          name_bn: string | null;
          kind: string;
          services: string[];
          description_en: string | null;
          description_bn: string | null;
          division_slug: string | null;
          city: string | null;
          address: string | null;
          phone: string | null;
          website: string | null;
          is_free: boolean | null;
          source_url: string;
          verified_at: string;
        };
        Insert: {
          id?: string;
          name_en: string;
          name_bn?: string | null;
          kind: string;
          services?: string[];
          description_en?: string | null;
          description_bn?: string | null;
          division_slug?: string | null;
          city?: string | null;
          address?: string | null;
          phone?: string | null;
          website?: string | null;
          is_free?: boolean | null;
          source_url: string;
          verified_at: string;
        };
        Update: {
          id?: string;
          name_en?: string;
          name_bn?: string | null;
          kind?: string;
          services?: string[];
          description_en?: string | null;
          description_bn?: string | null;
          division_slug?: string | null;
          city?: string | null;
          address?: string | null;
          phone?: string | null;
          website?: string | null;
          is_free?: boolean | null;
          source_url?: string;
          verified_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'support_organizations_division_slug_fkey';
            columns: ['division_slug'];
            isOneToOne: false;
            referencedRelation: 'divisions';
            referencedColumns: ['slug'];
          },
        ];
      };
      universities: {
        Row: {
          id: string;
          name_en: string;
          name_bn: string | null;
          type: string;
          division_slug: string | null;
          city: string | null;
          website: string | null;
          source_url: string | null;
        };
        Insert: {
          id?: string;
          name_en: string;
          name_bn?: string | null;
          type: string;
          division_slug?: string | null;
          city?: string | null;
          website?: string | null;
          source_url?: string | null;
        };
        Update: {
          id?: string;
          name_en?: string;
          name_bn?: string | null;
          type?: string;
          division_slug?: string | null;
          city?: string | null;
          website?: string | null;
          source_url?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'universities_division_slug_fkey';
            columns: ['division_slug'];
            isOneToOne: false;
            referencedRelation: 'divisions';
            referencedColumns: ['slug'];
          },
        ];
      };
      user_quests: {
        Row: {
          user_id: string;
          quest_id: string;
          date: string;
          completed_at: string;
        };
        Insert: {
          user_id: string;
          quest_id: string;
          date: string;
          completed_at?: string;
        };
        Update: {
          user_id?: string;
          quest_id?: string;
          date?: string;
          completed_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_quests_quest_id_fkey';
            columns: ['quest_id'];
            isOneToOne: false;
            referencedRelation: 'quests';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'user_quests_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      xp_events: {
        Row: {
          id: number;
          user_id: string;
          amount: number;
          reason: string;
          created_at: string;
        };
        Insert: {
          id?: number;
          user_id: string;
          amount: number;
          reason: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string;
          amount?: number;
          reason?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'xp_events_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      book_slot: {
        Args: {
          p_slot_id: string;
          p_notes?: string;
        };
        Returns: Database['public']['Tables']['bookings']['Row'];
      };
      cancel_booking: {
        Args: {
          p_booking_id: string;
        };
        Returns: Database['public']['Tables']['bookings']['Row'];
      };
      complete_quest: {
        Args: {
          p_code: string;
        };
        Returns: {
          completed: boolean;
          xp: number;
          level: number;
        }[];
      };
      get_comments: {
        Args: {
          p_post_id: string;
        };
        Returns: {
          id: string;
          post_id: string;
          alias_display: string;
          body: string;
          created_at: string;
          is_mine: boolean;
        }[];
      };
      get_feed: {
        Args: {
          p_limit?: number;
          p_before?: string;
          p_tag?: string;
        };
        Returns: {
          id: string;
          alias_display: string;
          body: string;
          tags: string[];
          is_anonymous: boolean;
          like_count: number;
          comment_count: number;
          created_at: string;
          is_mine: boolean;
          liked_by_me: boolean;
          is_hidden: boolean;
        }[];
      };
      get_my_quests: {
        Args: never;
        Returns: {
          id: string;
          code: string;
          title_en: string;
          title_bn: string;
          xp_reward: number;
          type: string;
          completion: string;
          completed: boolean;
        }[];
      };
      is_post_visible: {
        Args: {
          p_post_id: string;
        };
        Returns: boolean;
      };
      refresh_mentor_slots: {
        Args: {
          p_days?: number;
        };
        Returns: number;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database['public'];

export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row'];
export type TablesInsert<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Update'];
export type Functions<T extends keyof PublicSchema['Functions']> = PublicSchema['Functions'][T];
