/**
 * Generates the reference-data seed files from the verified research data in supabase/data/.
 *
 *   supabase/data/*.json   verified data with sources and verbatim evidence (see docs/DATA_SOURCES.md)
 *   supabase/data/overrides.json   curated edits: Bangla translations, normalised hours, exclusions
 *
 * Only entries marked VERIFIED are seeded. Output is idempotent (upserts on natural keys).
 * Usage: npm run db:seed:build
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const DATA = path.join(ROOT, 'supabase', 'data');
const SEED = path.join(ROOT, 'supabase', 'seed');

type Json = Record<string, unknown>;

// eslint-disable-next-line @typescript-eslint/no-unnecessary-type-parameters -- typed JSON loader: each caller declares the shape it expects
function load<T>(file: string): T {
  return JSON.parse(readFileSync(path.join(DATA, file), 'utf8')) as T;
}

/** SQL literal for strings, numbers, booleans, null and text arrays. */
function lit(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return `'${value.replace(/'/g, "''")}'`;
  if (Array.isArray(value)) {
    return value.length === 0 ? `'{}'::text[]` : `array[${value.map(lit).join(', ')}]::text[]`;
  }
  throw new Error(`Unsupported seed value: ${JSON.stringify(value)}`);
}

function row(values: unknown[]): string {
  return `  (${values.map(lit).join(', ')})`;
}

function upsert(
  table: string,
  columns: string[],
  rows: unknown[][],
  conflict: string,
  updateCols: string[],
) {
  if (rows.length === 0) return `-- ${table}: no verified rows yet\n`;
  const updates = updateCols.map((c) => `${c} = excluded.${c}`).join(', ');
  return `insert into public.${table} (${columns.join(', ')}) values\n${rows.map(row).join(',\n')}\non conflict ${conflict} do update set ${updates};\n`;
}

const header = (title: string, sources: string) =>
  `-- ${title}\n-- GENERATED by scripts/build-seed.ts from supabase/data/. Do not edit by hand.\n-- Sources and verification dates: docs/DATA_SOURCES.md${sources ? `; ${sources}` : ''}\n\n`;

const overrides = load<{
  helplines: Record<string, Json>;
  organizations: Record<string, Json>;
  calendar: { _skip_titles: string[]; title_bn: Record<string, string> };
}>('overrides.json');

// ------------------------------------------------------------------------------------------------
// 01 reference: divisions, districts, universities, quests
// ------------------------------------------------------------------------------------------------
const DIVISIONS = [
  ['dhaka', 'Dhaka', 'ঢাকা', 1],
  ['khulna', 'Khulna', 'খুলনা', 2],
  ['chattogram', 'Chattogram', 'চট্টগ্রাম', 3],
  ['rajshahi', 'Rajshahi', 'রাজশাহী', 4],
  ['sylhet', 'Sylhet', 'সিলেট', 5],
  ['rangpur', 'Rangpur', 'রংপুর', 6],
  ['mymensingh', 'Mymensingh', 'ময়মনসিংহ', 7],
  ['barishal', 'Barishal', 'বরিশাল', 8],
];

const districts = load<{ checked: string; districts: Json[] }>('districts.json');
const universities = load<{ checked: string; universities: Json[] }>('universities.json');

const QUESTS = [
  ['morning_checkin', 'Check in with your mood', 'আজকের মুড লিখে রাখুন', 50, 'daily', 'auto', 1],
  [
    'breathing_478',
    'Do a breathing exercise',
    'একটি শ্বাস-প্রশ্বাসের অনুশীলন করুন',
    100,
    'daily',
    'auto',
    2,
  ],
  [
    'read_article',
    'Read one self-care article',
    'নিজের যত্ন নিয়ে একটি লেখা পড়ুন',
    30,
    'daily',
    'manual',
    3,
  ],
  ['write_journal', 'Write in your journal', 'জার্নালে কিছু লিখুন', 40, 'daily', 'auto', 4],
  [
    'community_support',
    'Share or support someone in the Adda',
    'আড্ডায় কিছু শেয়ার করুন বা কাউকে সাহস দিন',
    150,
    'weekly',
    'auto',
    1,
  ],
];

const reference =
  header(
    'Reference data: geography, universities, quests',
    `divisions https://bangladesh.gov.bd/views/division-list`,
  ) +
  `-- Divisions (8)\n` +
  upsert('divisions', ['slug', 'name_en', 'name_bn', 'sort_order'], DIVISIONS, '(slug)', [
    'name_en',
    'name_bn',
    'sort_order',
  ]) +
  `\n-- Districts (${districts.districts.length}), checked ${districts.checked}\n` +
  upsert(
    'districts',
    ['slug', 'division_slug', 'name_en', 'name_bn'],
    districts.districts.map((d) => [d.slug, d.division_slug, d.name_en, d.name_bn]),
    '(slug)',
    ['division_slug', 'name_en', 'name_bn'],
  ) +
  `\n-- Universities (${universities.universities.length}), checked ${universities.checked}\n` +
  // universities has a unique name_en; ids are generated.
  upsert(
    'universities',
    ['name_en', 'name_bn', 'type', 'division_slug', 'city', 'website', 'source_url'],
    universities.universities.map((u) => [
      u.name_en,
      u.name_bn ?? null,
      u.type,
      u.division_slug,
      u.city,
      u.website,
      u.source_url,
    ]),
    '(name_en)',
    ['name_bn', 'type', 'division_slug', 'city', 'website', 'source_url'],
  ) +
  `\n-- Quests referenced by private.record_activity(). XP values carried over from the MVP.\n` +
  upsert(
    'quests',
    ['code', 'title_en', 'title_bn', 'xp_reward', 'type', 'completion', 'sort_order'],
    QUESTS,
    '(code)',
    ['title_en', 'title_bn', 'xp_reward', 'type', 'completion', 'sort_order'],
  );

// ------------------------------------------------------------------------------------------------
// 02 safety: helplines, support organisations, practitioner directory
// ------------------------------------------------------------------------------------------------
const safetyData = load<{ checked: string; helplines: Json[]; organizations: Json[] }>(
  'helplines_orgs.json',
);
const practitioners = load<{ checked: string; practitioners: Json[] }>('practitioners.json');
const verified = (x: Json) => x.status === 'VERIFIED';

const helplineRows = safetyData.helplines.filter(verified).map((h) => {
  const o = overrides.helplines[String(h.number)] as Json | undefined;
  if (!o) throw new Error(`Missing overrides for helpline ${String(h.number)}`);
  return [
    o.name ?? String(h.name).replace(/\s+\d{3,5}$/, ''),
    h.number,
    h.description_en,
    o.description_bn,
    o.hours,
    h.category,
    h.is_toll_free,
    h.source_url,
    safetyData.checked,
    o.sort_order ?? 10,
  ];
});

const orgRows = safetyData.organizations.filter(verified).map((org) => {
  const o = overrides.organizations[String(org.name_en)] ?? {};
  const pick = (key: string) => (key in o ? o[key] : org[key]);
  return [
    org.name_en,
    pick('name_bn'),
    org.kind,
    pick('services'),
    pick('description_en'),
    o.description_bn ?? null,
    org.division_slug,
    org.city,
    org.address,
    pick('phone'),
    org.website,
    org.is_free,
    org.source_url,
    safetyData.checked,
  ];
});

const practitionerRows = practitioners.practitioners
  .filter(verified)
  .map((p) => [
    p.full_name,
    p.title,
    p.profession,
    p.credentials ?? null,
    p.organization,
    p.specialties ?? [],
    p.languages ?? [],
    p.division_slug,
    p.city,
    p.modes ?? [],
    p.booking_url,
    p.profile_url ?? null,
    p.profile_url ?? p.booking_url,
    practitioners.checked,
  ]);

const safety =
  header('Safety data: helplines, support organisations, practitioner directory', '') +
  `-- Helplines: VERIFIED entries only (Kaan Pete Roi is excluded until re-verified).\n` +
  upsert(
    'helplines',
    [
      'name',
      'number',
      'description_en',
      'description_bn',
      'hours',
      'category',
      'is_toll_free',
      'source_url',
      'verified_at',
      'sort_order',
    ],
    helplineRows,
    '(number)',
    [
      'name',
      'description_en',
      'description_bn',
      'hours',
      'category',
      'is_toll_free',
      'source_url',
      'verified_at',
      'sort_order',
    ],
  ) +
  `\n-- Support organisations: VERIFIED entries only.\n` +
  upsert(
    'support_organizations',
    [
      'name_en',
      'name_bn',
      'kind',
      'services',
      'description_en',
      'description_bn',
      'division_slug',
      'city',
      'address',
      'phone',
      'website',
      'is_free',
      'source_url',
      'verified_at',
    ],
    orgRows,
    '(name_en)',
    [
      'name_bn',
      'kind',
      'services',
      'description_en',
      'description_bn',
      'division_slug',
      'city',
      'address',
      'phone',
      'website',
      'is_free',
      'source_url',
      'verified_at',
    ],
  ) +
  `\n-- Practitioner directory (build plan rule 8 amendment): real professionals' public listings.\n` +
  `-- The app links to booking_url on the professional's own official site; Bondhu never books.\n` +
  upsert(
    'practitioners',
    [
      'full_name',
      'title',
      'profession',
      'credentials',
      'organization',
      'specialties',
      'languages',
      'division_slug',
      'city',
      'modes',
      'booking_url',
      'profile_url',
      'source_url',
      'verified_at',
    ],
    practitionerRows,
    '(full_name, organization)',
    [
      'title',
      'profession',
      'credentials',
      'specialties',
      'languages',
      'division_slug',
      'city',
      'modes',
      'booking_url',
      'profile_url',
      'source_url',
      'verified_at',
    ],
  );

// ------------------------------------------------------------------------------------------------
// 03 content: calendar, resources, careers (resources/careers appear once their data exists)
// ------------------------------------------------------------------------------------------------
const calendar = load<{ checked: string; events: Json[] }>('calendar.json');
const calendarRows = calendar.events
  .filter((e) => !overrides.calendar._skip_titles.includes(String(e.title_en)))
  .map((e) => {
    const titleBn = overrides.calendar.title_bn[String(e.title_en)] ?? e.title_bn;
    if (!titleBn) throw new Error(`Missing Bangla title for calendar event ${String(e.title_en)}`);
    return [
      e.kind,
      e.title_en,
      titleBn,
      e.starts_on,
      e.ends_on ?? null,
      e.is_approximate,
      e.source_url,
    ];
  });

let content =
  header('Content: cultural and academic calendar, resources, career paths', '') +
  `-- Calendar (${calendarRows.length} events), checked ${calendar.checked}\n` +
  upsert(
    'calendar_events',
    ['kind', 'title_en', 'title_bn', 'starts_on', 'ends_on', 'is_approximate', 'source_url'],
    calendarRows,
    '(kind, title_en, starts_on)',
    ['title_bn', 'ends_on', 'is_approximate', 'source_url'],
  ).replace(/'(\d{4}-\d{2}-\d{2})'/g, "'$1'::date");

if (existsSync(path.join(DATA, 'resources.json'))) {
  const resources = load<{ checked: string; resources: Json[] }>('resources.json');
  content +=
    `\n-- Resources (${resources.resources.length}), links checked ${resources.checked}\n` +
    upsert(
      'resources',
      [
        'title_en',
        'title_bn',
        'category',
        'url',
        'source_org',
        'language',
        'is_verified',
        'verified_at',
      ],
      resources.resources.map((r) => [
        r.title_en,
        r.title_bn ?? null,
        r.category,
        r.url,
        r.source_org,
        r.language,
        true,
        resources.checked,
      ]),
      '(url)',
      ['title_en', 'title_bn', 'category', 'source_org', 'language', 'is_verified', 'verified_at'],
    );
}

if (existsSync(path.join(DATA, 'careers.json'))) {
  const careers = load<{ careers: Json[] }>('careers.json');
  content +=
    `\n-- Career paths (${careers.careers.length}); entry-route facts are sourced in supabase/data/careers.json\n` +
    upsert(
      'career_paths',
      [
        'title_en',
        'title_bn',
        'sector',
        'description_en',
        'description_bn',
        'skills',
        'typical_entry_route_en',
        'typical_entry_route_bn',
      ],
      careers.careers.map((c) => [
        c.title_en,
        c.title_bn,
        c.sector,
        c.description_en,
        c.description_bn,
        c.skills,
        c.typical_entry_route_en,
        c.typical_entry_route_bn,
      ]),
      '(title_en)',
      [
        'title_bn',
        'sector',
        'description_en',
        'description_bn',
        'skills',
        'typical_entry_route_en',
        'typical_entry_route_bn',
      ],
    );
}

writeFileSync(path.join(SEED, '01_reference.sql'), reference);
writeFileSync(path.join(SEED, '02_safety.sql'), safety);
writeFileSync(path.join(SEED, '03_content.sql'), content);

console.log(
  `Seed built: ${DIVISIONS.length} divisions, ${districts.districts.length} districts, ${universities.universities.length} universities, ` +
    `${helplineRows.length} helplines, ${orgRows.length} organisations, ${practitionerRows.length} practitioners, ${calendarRows.length} calendar events`,
);
